root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "import"
  - "unused-imports"
extends:
  - next
  - next/core-web-vitals
  - prettier
rules:
  "@next/next/no-img-element": off
  no-console:
    - error
    - allow:
        - warn
        - error
        - debug
        - info
  unused-imports/no-unused-imports-ts: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: "^_"
      args: all
      argsIgnorePattern: "^_"
  "import/order":
    - error
    - groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
        - index
        - object
        - type
      newlines-between: always
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: true
      pathGroups:
        - pattern: "{react, next}/**}"
          group: external
          position: before
        - pattern: "@/**"
          group: internal
          position: before
