import Analytics from "@/libs/GoogleAnalytics"
import { courgette, notojp } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <Analytics />
      </head>
      <body className={`${notojp.variable} ${courgette.variable} font-notojp`}>{children}</body>
    </html>
  );
}
