import './globals.css'
import { Courgette, Noto_Sans_JP } from 'next/font/google'

const notojp = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-notojp",
});

const courgette = Courgette({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-courgette",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${notojp.variable} ${courgette.variable} font-notojp`}>{children}</body>
    </html>
  )
}
