import { PrismicPreview } from "@prismicio/next"

import Analytics from "@/libs/GoogleAnalytics"

import "./globals.css";
import { courgette, notojp } from "./fonts";
import { repositoryName } from '../../prismicio';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <Analytics />
      </head>
      <body className={`${notojp.variable} ${courgette.variable} font-notojp`}>{children}</body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
